services:
  authservice:
    image: ${DOCKER_REGISTRY-}authservice
    build:
      context: .
      dockerfile: Services/AuthService/Dockerfile
    ports:
        - "5001:5001"
        - "6001:6002"
    environment:
        - ASPNETCORE_URLS=http://+:5001;
        
  noteservice:
    image: ${DOCKER_REGISTRY-}noteservice
    build:
      context: .
      dockerfile: Services/NotesService/Dockerfile  
    ports:
      - "5002:5002"
      - "6002:6002"
    environment:
        - ASPNETCORE_URLS=http://+:5002;
